# Generated by Django 4.2 on 2023-08-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_rename_beverages_order_beverage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_name',
            field=models.CharField(default='Customer', max_length=100),
            preserve_default=False,
        ),
    ]
